# Generated by Django 6.0.3 on 2026-04-19 03:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0002_offreemploi_adhesion_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='date_adhesion',
        ),
        migrations.AddField(
            model_name='membre',
            name='code_membre',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='membre',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membre',
            name='email',
            field=models.EmailField(default='diamsbonheurpaku@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membre',
            name='telephone',
            field=models.CharField(default='0990000000', max_length=20),
            preserve_default=False,
        ),
    ]
