# Generated by Django 6.0.3 on 2026-04-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0004_candidature'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='email',
            field=models.EmailField(default='diamsbonheurpaku@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
