# Generated by Django 6.0.3 on 2026-04-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0005_candidature_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='email',
            field=models.EmailField(default='default@email.com', max_length=254, unique=True),
        ),
    ]
