# Generated by Django 6.0.3 on 2026-04-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0006_alter_candidature_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='membre',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
