# Generated by Django 6.0.3 on 2026-04-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0007_alter_candidature_email_alter_membre_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
