# Generated by Django 6.0.3 on 2026-04-30 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0009_membre_bio_membre_cv_membre_photo_membre_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='membres.membre'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='fonction',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='membre',
            name='postnom',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
